In [5]:
from pandas import set_option
from pandas import read_csv

In [6]:
from pandas import read_csv

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 
data = read_csv('pima-indians-diabetes.data.csv',names = names)

In [7]:
data.head(20)

,preg,plas,pres,skin,test,mass,pedi,age,class
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0
5,0,137,40,35,168,43.1,2.288,33,1
6,5,116,74,0,0,25.6,0.201,30,0
7,3,78,50,32,88,31,0.248,26,1
8,10,115,0,0,0,35.3,0.134,29,0
9,2,197,70,45,543,30.5,0.158,53,1
10,8,125,96,0,0,0,0.232,54,1
11,4,110,92,0,0,37.6,0.191,30,0
12,10,168,74,0,0,38,0.537,34,1
13,10,139,80,0,0,27.1,1.441,57,0
14,1,189,60,23,846,30.1,0.398,59,1
15,5,166,72,19,175,25.8,0.587,51,1
16,7,100,0,0,0,30,0.484,32,1
17,0,118,84,47,230,45.8,0.551,31,1
18,7,107,74,0,0,29.6,0.254,31,1
19,1,103,30,38,83,43.3,0.183,33,0

In [8]:
## Univariate plots
#   histograms/ Density plots/ box and whisker plots
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
sns.set_style("whitegrid");
sns.pairplot('pima-indians-diabetes.data.csv');
plt.show()

TypeError: 'data' must be pandas DataFrame object, not: <class 'str'>